"""Plugin Platform v2 public contracts."""

from nocturna_engine.core.plugin_v2.contracts import (
    BaseToolV2,
    CapabilityDescriptor,
    CompatibilityInfo,
    EnvironmentSecretAccessor,
    ExecutionRequirements,
    HealthProfile,
    InMemoryMetricsCollector,
    InMemoryRuntimeCache,
    LocalTempStorageProvider,
    PluginManifest,
    PluginRuntimeContext,
    ToolV2Protocol,
)
from nocturna_engine.core.plugin_v2.cache import ScanResultCache, build_result_fingerprint
from nocturna_engine.core.plugin_v2.events import (
    DEFAULT_EVENT_ALIASES,
    EventV2,
    build_reverse_aliases,
    normalize_event_payload,
)
from nocturna_engine.core.plugin_v2.docs import generate_plugin_docs
from nocturna_engine.core.plugin_v2.health import PluginHealthStatus, PreflightHealthOrchestrator
from nocturna_engine.core.plugin_v2.legacy_adapter import LegacyToolAdapter
from nocturna_engine.core.plugin_v2.planner import AIPlan, CapabilityAwarePlanner, PlanStep, parse_ai_dsl
from nocturna_engine.core.plugin_v2.policy import (
    EgressDecision,
    EgressEndpoint,
    EgressPolicyEvaluator,
    POLICY_REASON_DENIED_EGRESS_CIDR,
    POLICY_REASON_DENIED_EGRESS_HOST,
    POLICY_REASON_DENIED_EGRESS_PORT,
    POLICY_REASON_DENIED_EGRESS_PROTOCOL,
    POLICY_REASON_DENIED_FILESYSTEM,
    POLICY_REASON_DENIED_NETWORK,
    POLICY_REASON_DENIED_SUBPROCESS,
    POLICY_REASON_INVALID,
    PluginPolicy,
    PluginPolicyEngine,
    PolicyBuildResult,
    PolicyDecision,
)
from nocturna_engine.core.plugin_v2.registry import (
    DeterministicPluginRegistry,
    PluginRegistration,
    build_manifest_from_tool_class,
    declare_plugin,
)
from nocturna_engine.core.plugin_v2.reliability import CircuitBreakerRegistry, CircuitState

__all__ = [
    "AIPlan",
    "BaseToolV2",
    "CapabilityAwarePlanner",
    "CapabilityDescriptor",
    "CircuitBreakerRegistry",
    "CircuitState",
    "CompatibilityInfo",
    "DEFAULT_EVENT_ALIASES",
    "DeterministicPluginRegistry",
    "EgressDecision",
    "EgressEndpoint",
    "EgressPolicyEvaluator",
    "EnvironmentSecretAccessor",
    "EventV2",
    "ExecutionRequirements",
    "HealthProfile",
    "InMemoryMetricsCollector",
    "InMemoryRuntimeCache",
    "LegacyToolAdapter",
    "LocalTempStorageProvider",
    "PlanStep",
    "PluginHealthStatus",
    "PluginManifest",
    "PluginPolicy",
    "PluginPolicyEngine",
    "PluginRegistration",
    "PluginRuntimeContext",
    "PolicyBuildResult",
    "PolicyDecision",
    "POLICY_REASON_DENIED_EGRESS_CIDR",
    "POLICY_REASON_DENIED_EGRESS_HOST",
    "POLICY_REASON_DENIED_EGRESS_PORT",
    "POLICY_REASON_DENIED_EGRESS_PROTOCOL",
    "POLICY_REASON_DENIED_FILESYSTEM",
    "POLICY_REASON_DENIED_NETWORK",
    "POLICY_REASON_DENIED_SUBPROCESS",
    "POLICY_REASON_INVALID",
    "PreflightHealthOrchestrator",
    "ScanResultCache",
    "ToolV2Protocol",
    "build_result_fingerprint",
    "build_reverse_aliases",
    "build_manifest_from_tool_class",
    "declare_plugin",
    "generate_plugin_docs",
    "normalize_event_payload",
    "parse_ai_dsl",
]
