"""Comprehensive edge-case tests for NocturnaEngine orchestration."""

from __future__ import annotations

import asyncio
from typing import Any, ClassVar
from unittest.mock import AsyncMock, patch
from uuid import uuid4

import pytest

from nocturna_engine.core.engine import NocturnaEngine
from nocturna_engine.interfaces.base_analyzer import BaseAnalyzer
from nocturna_engine.interfaces.base_reporter import BaseReporter
from nocturna_engine.interfaces.base_tool import BaseTool
from nocturna_engine.models.finding import Finding, SeverityLevel
from nocturna_engine.models.scan_request import ScanRequest
from nocturna_engine.models.scan_result import ScanResult
from nocturna_engine.models.target import Target


# ---------------------------------------------------------------------------
# Test doubles
# ---------------------------------------------------------------------------

def _make_request(**overrides: Any) -> ScanRequest:
    defaults: dict[str, Any] = {
        "targets": [Target(domain="example.com", scope=["example.com"])],
        "timeout_seconds": 5.0,
        "retries": 0,
        "concurrency_limit": 4,
    }
    defaults.update(overrides)
    return ScanRequest(**defaults)


class HealthyTool(BaseTool):
    name: ClassVar[str] = "healthy_tool"

    async def execute(self, request: ScanRequest) -> ScanResult:
        return ScanResult(
            request_id=request.request_id,
            tool_name=self.name,
            raw_output={"status": "ok"},
        )

    async def parse_output(
        self,
        raw_output: dict[str, Any] | list[Any] | str | None,
        request: ScanRequest,
    ) -> list[Finding]:
        target = request.targets[0].domain or str(request.targets[0].ip)
        return [
            Finding(
                title="Healthy finding",
                description="Found by healthy tool.",
                severity=SeverityLevel.LOW,
                tool=self.name,
                target=target or "unknown",
            )
        ]


class SecondHealthyTool(BaseTool):
    name: ClassVar[str] = "second_healthy_tool"

    async def execute(self, request: ScanRequest) -> ScanResult:
        return ScanResult(
            request_id=request.request_id,
            tool_name=self.name,
            raw_output={"status": "ok2"},
        )

    async def parse_output(
        self,
        raw_output: dict[str, Any] | list[Any] | str | None,
        request: ScanRequest,
    ) -> list[Finding]:
        return []


class FailingTool(BaseTool):
    name: ClassVar[str] = "failing_tool"

    async def execute(self, request: ScanRequest) -> ScanResult:
        raise RuntimeError("kaboom")

    async def parse_output(
        self,
        raw_output: dict[str, Any] | list[Any] | str | None,
        request: ScanRequest,
    ) -> list[Finding]:
        return []


class SlowTool(BaseTool):
    name: ClassVar[str] = "slow_tool"
    timeout_seconds: ClassVar[float] = 1.0

    async def execute(self, request: ScanRequest) -> ScanResult:
        await asyncio.sleep(300)
        return ScanResult(
            request_id=request.request_id,
            tool_name=self.name,
            raw_output={},
        )

    async def parse_output(
        self,
        raw_output: dict[str, Any] | list[Any] | str | None,
        request: ScanRequest,
    ) -> list[Finding]:
        return []


class StubAnalyzer(BaseAnalyzer):
    name: ClassVar[str] = "stub_analyzer"

    async def analyze(
        self, scan_results: list[ScanResult], request: ScanRequest
    ) -> list[Finding]:
        target = request.targets[0].domain or str(request.targets[0].ip)
        return [
            Finding(
                title="Analyzer extra finding",
                description="Generated by stub analyzer.",
                severity=SeverityLevel.INFO,
                tool=self.name,
                target=target or "unknown",
            )
        ]


class FailingAnalyzer(BaseAnalyzer):
    name: ClassVar[str] = "failing_analyzer"

    async def analyze(
        self, scan_results: list[ScanResult], request: ScanRequest
    ) -> list[Finding]:
        raise RuntimeError("analyzer exploded")


class StubReporter(BaseReporter):
    name: ClassVar[str] = "stub_reporter"

    async def generate_report(
        self,
        request: ScanRequest,
        scan_results: list[ScanResult],
        findings: list[Finding],
    ) -> dict[str, Any]:
        return {
            "request_id": request.request_id,
            "total_findings": len(findings),
        }


class FailingReporter(BaseReporter):
    name: ClassVar[str] = "failing_reporter"

    async def generate_report(
        self,
        request: ScanRequest,
        scan_results: list[ScanResult],
        findings: list[Finding],
    ) -> dict[str, Any]:
        raise RuntimeError("reporter exploded")


class MultiFindingTool(BaseTool):
    """Produces multiple findings with same fingerprint for dedup testing."""
    name: ClassVar[str] = "multi_finding_tool"

    async def execute(self, request: ScanRequest) -> ScanResult:
        target = request.targets[0].domain or str(request.targets[0].ip)
        return ScanResult(
            request_id=request.request_id,
            tool_name=self.name,
            raw_output={},
            findings=[
                Finding(
                    title="Duplicate finding",
                    description="First occurrence for dedup.",
                    severity=SeverityLevel.HIGH,
                    tool=self.name,
                    target=target or "unknown",
                    cwe="CWE-89",
                    evidence={"endpoint": "/api"},
                    metadata={"idx": "first"},
                ),
                Finding(
                    title="Duplicate finding",
                    description="Second occurrence for dedup.",
                    severity=SeverityLevel.HIGH,
                    tool=self.name,
                    target=target or "unknown",
                    cwe="CWE-89",
                    evidence={"endpoint": "/api"},
                    metadata={"idx": "second"},
                ),
                Finding(
                    title="Unique finding",
                    description="Unique finding no collision.",
                    severity=SeverityLevel.LOW,
                    tool=self.name,
                    target=target or "unknown",
                ),
            ],
        )

    async def parse_output(
        self,
        raw_output: dict[str, Any] | list[Any] | str | None,
        request: ScanRequest,
    ) -> list[Finding]:
        return []


# ---------------------------------------------------------------------------
# Initialization tests
# ---------------------------------------------------------------------------


async def test_engine_init_defaults():
    """Engine creates all core components with defaults."""
    engine = NocturnaEngine()
    assert engine.plugin_manager is not None
    assert engine.event_bus is not None
    assert engine.pipeline is not None
    assert engine.config_service is not None
    assert engine.logging_service is not None
    assert engine.finding_index is not None
    assert engine._started is False
    assert engine._analyzers == []
    assert engine._reporters == []


async def test_engine_init_with_injected_deps():
    """Engine accepts injected dependencies."""
    from nocturna_engine.core.event_bus import EventBus
    from nocturna_engine.core.pipeline import Pipeline
    from nocturna_engine.core.plugin_manager import PluginManager

    eb = EventBus()
    pm = PluginManager(event_bus=eb)
    pl = Pipeline()
    engine = NocturnaEngine(plugin_manager=pm, event_bus=eb, pipeline=pl)
    assert engine.plugin_manager is pm
    assert engine.event_bus is eb
    assert engine.pipeline is pl


async def test_engine_init_with_analyzers_and_reporters():
    """Engine stores injected analyzers and reporters."""
    analyzer = StubAnalyzer()
    reporter = StubReporter()
    engine = NocturnaEngine(analyzers=[analyzer], reporters=[reporter])
    assert analyzer in engine._analyzers
    assert reporter in engine._reporters


# ---------------------------------------------------------------------------
# Registration tests
# ---------------------------------------------------------------------------


async def test_register_tool_returns_name():
    """register_tool returns normalized plugin name."""
    engine = NocturnaEngine()
    name = engine.register_tool(HealthyTool)
    assert name == "healthy_tool"


async def test_register_multiple_tools():
    """Multiple tools can be registered."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)
    engine.register_tool(SecondHealthyTool)
    tools = engine.plugin_manager.list_registered_tools()
    assert "healthy_tool" in tools
    assert "second_healthy_tool" in tools


async def test_register_analyzer():
    """register_analyzer appends to internal list."""
    engine = NocturnaEngine()
    a1 = StubAnalyzer()
    a2 = FailingAnalyzer()
    engine.register_analyzer(a1)
    engine.register_analyzer(a2)
    assert engine._analyzers == [a1, a2]


async def test_register_reporter():
    """register_reporter appends to internal list."""
    engine = NocturnaEngine()
    r1 = StubReporter()
    r2 = FailingReporter()
    engine.register_reporter(r1)
    engine.register_reporter(r2)
    assert engine._reporters == [r1, r2]


# ---------------------------------------------------------------------------
# Start / stop lifecycle tests
# ---------------------------------------------------------------------------


async def test_start_sets_started_flag():
    """Engine.start() sets _started = True."""
    engine = NocturnaEngine()
    assert engine._started is False
    await engine.start()
    assert engine._started is True
    await engine.stop()


async def test_start_idempotent():
    """Calling start() twice does not error."""
    engine = NocturnaEngine()
    await engine.start()
    await engine.start()  # no-op
    assert engine._started is True
    await engine.stop()


async def test_stop_resets_started_flag():
    """Engine.stop() resets _started = False."""
    engine = NocturnaEngine()
    await engine.start()
    await engine.stop()
    assert engine._started is False


async def test_stop_idempotent():
    """Calling stop() when not started is a no-op."""
    engine = NocturnaEngine()
    await engine.stop()  # no error
    assert engine._started is False


# ---------------------------------------------------------------------------
# Async context manager tests
# ---------------------------------------------------------------------------


async def test_async_context_manager_starts_and_stops():
    """async with engine: starts and stops engine."""
    engine = NocturnaEngine()
    async with engine as ctx:
        assert ctx is engine
        assert engine._started is True
    assert engine._started is False


async def test_async_context_manager_stops_on_exception():
    """Engine stops even if body raises."""
    engine = NocturnaEngine()
    with pytest.raises(ValueError, match="forced"):
        async with engine:
            assert engine._started is True
            raise ValueError("forced")
    assert engine._started is False


# ---------------------------------------------------------------------------
# run_scan lifecycle tests
# ---------------------------------------------------------------------------


async def test_run_scan_auto_starts_engine():
    """run_scan calls start() if not already started."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)
    request = _make_request()
    context = await engine.run_scan(request)
    assert engine._started is True
    assert "scan_results" in context
    await engine.stop()


async def test_run_scan_end_to_end_with_tool_analyzer_reporter():
    """Full pipeline: scan → analyze → report."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)
    engine.register_analyzer(StubAnalyzer())
    engine.register_reporter(StubReporter())

    async with engine:
        context = await engine.run_scan(_make_request())

    assert len(context["scan_results"]) == 1
    assert context["scan_results"][0].success is True
    assert len(context["findings"]) >= 2  # tool + analyzer
    assert "stub_reporter" in context["reports"]


async def test_run_scan_with_no_tools_registered():
    """Scan with no tools yields empty results and fallback report."""
    engine = NocturnaEngine()
    async with engine:
        context = await engine.run_scan(_make_request())
    assert context.get("scan_results", []) == []
    # Should have summary fallback report
    assert "summary" in context.get("reports", {})


async def test_run_scan_with_tool_names_filter():
    """Only selected tools run when tool_names filter is specified."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)
    engine.register_tool(SecondHealthyTool)
    request = _make_request(tool_names=["healthy_tool"])

    async with engine:
        context = await engine.run_scan(request)

    tool_names_run = [r.tool_name for r in context["scan_results"]]
    assert "healthy_tool" in tool_names_run
    assert "second_healthy_tool" not in tool_names_run


async def test_run_scan_tool_names_filter_unknown_tool():
    """Requesting unknown tool name results in empty results."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)
    request = _make_request(tool_names=["nonexistent_tool"])

    async with engine:
        context = await engine.run_scan(request)

    assert context.get("scan_results", []) == []


# ---------------------------------------------------------------------------
# Tool failure isolation tests
# ---------------------------------------------------------------------------


async def test_one_tool_fails_others_succeed():
    """Failing tool doesn't prevent healthy tool from completing."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)
    engine.register_tool(FailingTool)
    request = _make_request(tool_names=["healthy_tool", "failing_tool"])

    async with engine:
        context = await engine.run_scan(request)

    results = {r.tool_name: r for r in context["scan_results"]}
    assert results["healthy_tool"].success is True
    assert results["failing_tool"].success is False


async def test_all_tools_fail_still_produces_report():
    """Even if all tools fail, report step still runs."""
    engine = NocturnaEngine()
    engine.register_tool(FailingTool)
    request = _make_request(tool_names=["failing_tool"])

    async with engine:
        context = await engine.run_scan(request)

    results = {r.tool_name: r for r in context["scan_results"]}
    assert results["failing_tool"].success is False
    assert "reports" in context


# ---------------------------------------------------------------------------
# Analyzer and reporter failure isolation tests
# ---------------------------------------------------------------------------


async def test_failing_analyzer_does_not_break_pipeline():
    """A failing analyzer is caught; other findings still produced."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)
    engine.register_analyzer(FailingAnalyzer())
    engine.register_analyzer(StubAnalyzer())

    async with engine:
        context = await engine.run_scan(_make_request())

    # Analyzer failure is swallowed; at least tool + stub_analyzer findings exist
    assert len(context["findings"]) >= 1


async def test_failing_reporter_falls_back_to_summary():
    """When all reporters fail, a summary fallback report is generated."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)
    engine.register_reporter(FailingReporter())

    async with engine:
        context = await engine.run_scan(_make_request())

    # fallback summary should be present
    assert "summary" in context["reports"]


# ---------------------------------------------------------------------------
# Event publishing tests
# ---------------------------------------------------------------------------


async def test_on_scan_started_event():
    """on_scan_started event is published with request_id."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)
    events: list[dict[str, Any]] = []

    async def handler(event: Any) -> None:
        events.append({"name": event.name, "payload": dict(event.payload)})

    engine.subscribe("on_scan_started", handler)
    async with engine:
        request = _make_request()
        await engine.run_scan(request)

    assert len(events) >= 1
    assert events[0]["name"] == "on_scan_started"
    assert events[0]["payload"]["request_id"] == request.request_id


async def test_on_scan_finished_event():
    """on_scan_finished event is published after scan completes."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)
    events: list[str] = []

    async def handler(event: Any) -> None:
        events.append(event.name)

    engine.subscribe("on_scan_finished", handler)
    async with engine:
        await engine.run_scan(_make_request())

    assert "on_scan_finished" in events


async def test_on_finding_detected_events():
    """on_finding_detected is emitted for each unique finding."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)
    payloads: list[dict[str, Any]] = []

    async def handler(event: Any) -> None:
        payloads.append(dict(event.payload))

    engine.subscribe("on_finding_detected", handler)
    async with engine:
        await engine.run_scan(_make_request())

    assert len(payloads) >= 1
    for p in payloads:
        assert "finding_id" in p
        assert "severity" in p
        assert "fingerprint" in p


async def test_on_analyzer_error_event_published():
    """on_analyzer_error is emitted when an analyzer fails."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)
    engine.register_analyzer(FailingAnalyzer())
    events: list[str] = []

    async def handler(event: Any) -> None:
        events.append(event.name)

    engine.subscribe("on_analyzer_error", handler)
    async with engine:
        await engine.run_scan(_make_request())

    assert "on_analyzer_error" in events


async def test_on_reporter_error_event_published():
    """on_reporter_error is emitted when a reporter fails."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)
    engine.register_reporter(FailingReporter())
    events: list[str] = []

    async def handler(event: Any) -> None:
        events.append(event.name)

    engine.subscribe("on_reporter_error", handler)
    async with engine:
        await engine.run_scan(_make_request())

    assert "on_reporter_error" in events


async def test_subscribe_and_unsubscribe():
    """subscribe/unsubscribe properly manages handlers."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)
    events: list[str] = []

    async def handler(event: Any) -> None:
        events.append(event.name)

    engine.subscribe("on_scan_started", handler)
    engine.unsubscribe("on_scan_started", handler)

    async with engine:
        await engine.run_scan(_make_request())

    assert "on_scan_started" not in events


# ---------------------------------------------------------------------------
# Deduplication tests
# ---------------------------------------------------------------------------


async def test_fingerprint_dedup_in_analyze_step():
    """Findings with identical fingerprints are deduplicated in analyze step."""
    engine = NocturnaEngine()
    engine.register_tool(MultiFindingTool)

    async with engine:
        context = await engine.run_scan(_make_request())

    findings = context["findings"]
    fingerprints = [f.fingerprint for f in findings]
    # Should have unique fingerprints
    assert len(fingerprints) == len(set(fingerprints))


async def test_dedup_last_finding_wins():
    """When fingerprints collide, the last finding (by insertion order) wins."""
    engine = NocturnaEngine()
    request = _make_request()

    # Build scan results with duplicate fingerprints
    target = request.targets[0].domain or "unknown"
    f1 = Finding(
        finding_id="first-id",
        title="Shared title",
        description="First occurrence.",
        severity=SeverityLevel.HIGH,
        tool="test_tool",
        target=target,
        cwe="CWE-79",
        evidence={"endpoint": "/a"},
    )
    f2 = Finding(
        finding_id="second-id",
        title="Shared title",
        description="Second occurrence should win.",
        severity=SeverityLevel.HIGH,
        tool="test_tool",
        target=target,
        cwe="CWE-79",
        evidence={"endpoint": "/a"},
    )
    assert f1.fingerprint == f2.fingerprint

    result = engine._deduplicate_findings_by_fingerprint(
        [f1, f2], stage="test", request_id="test-req"
    )
    assert len(result) == 1
    assert result[0].finding_id == "second-id"


# ---------------------------------------------------------------------------
# Finding trend tracking (fingerprint index integration)
# ---------------------------------------------------------------------------


async def test_run_scan_populates_finding_trends():
    """run_scan updates finding_trends in context."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)

    async with engine:
        context = await engine.run_scan(_make_request())

    assert "finding_trends" in context
    assert "finding_trend_index_size" in context
    assert context["finding_trend_index_size"] >= 1


async def test_run_scan_trends_increment_across_runs():
    """Trend counts increment when running multiple scans."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)

    async with engine:
        ctx1 = await engine.run_scan(_make_request(request_id=str(uuid4())))
        ctx2 = await engine.run_scan(_make_request(request_id=str(uuid4())))

    for fp in ctx1.get("finding_trends", {}):
        assert ctx1["finding_trends"][fp]["count"] == 1
        if fp in ctx2.get("finding_trends", {}):
            assert ctx2["finding_trends"][fp]["count"] == 2


# ---------------------------------------------------------------------------
# Summary/fallback report tests
# ---------------------------------------------------------------------------


async def test_summary_report_contains_expected_keys():
    """Fallback summary report has standardized keys."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)

    async with engine:
        context = await engine.run_scan(_make_request())

    report = context["reports"]["summary"]
    assert "request_id" in report
    assert "targets" in report
    assert "tools_executed" in report
    assert "findings_total" in report
    assert "findings_by_severity" in report
    assert "errors" in report


async def test_summary_report_with_no_findings():
    """Summary report works when there are zero findings."""
    engine = NocturnaEngine()
    engine.register_tool(SecondHealthyTool)  # produces no findings

    async with engine:
        context = await engine.run_scan(_make_request())

    report = context["reports"]["summary"]
    assert report["findings_total"] == 0
    assert report["findings_by_severity"] == {}


# ---------------------------------------------------------------------------
# Pipeline configuration tests
# ---------------------------------------------------------------------------


async def test_default_pipeline_has_three_steps():
    """Default pipeline has scan, analyze, report steps."""
    engine = NocturnaEngine()
    step_names = [s.name for s in engine.pipeline._steps]
    assert step_names == ["scan", "analyze", "report"]


# ---------------------------------------------------------------------------
# Config edge cases
# ---------------------------------------------------------------------------


async def test_engine_with_empty_config():
    """Engine works when config returns empty dict."""

    class EmptyConfigService:
        def load(self) -> dict[str, Any]:
            return {}
        def get(self, key: str, default: Any = None) -> Any:
            return default

    engine = NocturnaEngine(config_service=EmptyConfigService())
    engine.register_tool(HealthyTool)
    async with engine:
        context = await engine.run_scan(_make_request())
    assert "scan_results" in context


async def test_engine_with_missing_features_key():
    """Config without 'features' key doesn't crash engine start."""

    class NoFeaturesConfigService:
        def load(self) -> dict[str, Any]:
            return {"engine": {"default_timeout_seconds": 10}}
        def get(self, key: str, default: Any = None) -> Any:
            return default

    engine = NocturnaEngine(config_service=NoFeaturesConfigService())
    await engine.start()
    assert engine._started is True
    await engine.stop()


async def test_engine_with_invalid_finding_index_path():
    """Engine survives invalid finding_index_path in config."""

    class BadIndexConfigService:
        def load(self) -> dict[str, Any]:
            return {
                "engine": {"finding_index_path": "/\x00/invalid/path"},
                "features": {},
            }
        def get(self, key: str, default: Any = None) -> Any:
            return default

    engine = NocturnaEngine(config_service=BadIndexConfigService())
    # Should not raise — logs warning and continues
    await engine.start()
    assert engine._started is True
    await engine.stop()


# ---------------------------------------------------------------------------
# Parametrized edge cases
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "tool_names",
    [
        None,  # all tools
        [],    # empty list → normalized to None by validator
        ["healthy_tool"],
        ["healthy_tool", "nonexistent"],
    ],
    ids=["all-tools", "empty-list", "specific-tool", "mixed-valid-invalid"],
)
async def test_run_scan_various_tool_name_filters(tool_names: list[str] | None):
    """Run scan with various tool_names filter shapes."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)
    engine.register_tool(SecondHealthyTool)

    request = _make_request(tool_names=tool_names)
    async with engine:
        context = await engine.run_scan(request)

    assert "scan_results" in context
    assert "reports" in context


@pytest.mark.parametrize(
    "metadata",
    [
        {},
        {"extra": "value"},
        {"dag_enabled": False},
        {"dag_phases": "recon"},
    ],
    ids=["empty", "custom-key", "dag-off", "dag-phases-string"],
)
async def test_run_scan_with_various_metadata(metadata: dict[str, Any]):
    """run_scan handles various metadata shapes without crashing."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)

    request = _make_request(metadata=metadata)
    async with engine:
        context = await engine.run_scan(request)

    assert "scan_results" in context


# ---------------------------------------------------------------------------
# Plugin catalog facade
# ---------------------------------------------------------------------------


async def test_plugin_catalog_describe_all():
    """plugins.describe_all returns registered tools."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)
    descriptions = engine.plugins.describe_all()
    assert "healthy_tool" in descriptions


async def test_plugin_catalog_describe_unknown_tool():
    """plugins.describe returns None for unregistered tool."""
    engine = NocturnaEngine()
    result = engine.plugins.describe("nonexistent_tool")
    assert result is None


# ---------------------------------------------------------------------------
# Sync facade test
# ---------------------------------------------------------------------------


def test_run_scan_sync():
    """Synchronous facade runs full scan."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)
    context = engine.run_scan_sync(_make_request())
    assert "scan_results" in context
    asyncio.run(engine.stop())


def test_run_scan_sync_raises_inside_event_loop():
    """run_scan_sync raises RuntimeError if already in async context."""
    engine = NocturnaEngine()
    engine.register_tool(HealthyTool)

    async def inner():
        with pytest.raises(RuntimeError, match="run_scan_sync cannot be used"):
            engine.run_scan_sync(_make_request())

    asyncio.run(inner())
